language: go

go:
  - "1.10"
  - 1.11
  - 1.12
  - tip

before_install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega/...

script:
  - ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --cover --trace --race -outputdir=./ ./...
