language: go
go:
  - 1.8
  - 1.9
  - "1.10"
  - 1.11
  - tip
install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin
script:
  - ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
